Repository SSWConsulting/SSW.SophieBot, pull requests merged in 2021-12, with the labels that each got.

#352 Enhance profile and status card
  src/bot/SSW.SophieBot.HttpClientComponents.PersonQuery/Actions/GetProfileWithBookingInfoAction.cs
  src/bot/SSW.SophieBot.HttpClientComponents.PersonQuery/Models/EmployeeWithBookingInfoModel.cs
  src/bot/SSW.SophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/common.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/icons.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/profile.en-us.lg
Labels: enhancement

#355 Fix who is free on monday
  src/bot/SSW.SophieBot.Components/Actions/EnrichDatatimeAction.cs
  src/bot/SSW.SophieBot.Components/Actions/EnrichDatatimeAction.schema
  src/bot/SSW.SophieBot.Components/ComponentHelper.cs
  src/bot/SSW.SophieBot.Components/Components/CommonComponent.cs
  src/bot/SSW.SophieBot.Components/Models/Datetime.cs
  src/bot/SSW.SophieBot.Components/Models/EnrichedDatetime.cs
  src/bot/SSW.SophieBot.Components/SSW.SophieBot.Components.csproj
  src/bot/SSW.SophieBot/SSWSophieBot.dialog
  src/bot/SSW.SophieBot/dialogs/GetAvailableExpertsByLocationDialog/GetAvailableExpertsByLocationDialog.dialog
  src/bot/SSW.SophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog
  src/bot/SSW.SophieBot/schemas/sdk.schema
Labels: bug

#354 Fix skill query exact match
  src/bot/SSW.SophieBot/SSWSophieBot.dialog
  src/bot/SSW.SophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetPeopleBySkills/GetPeopleBySkills.dialog
  src/bot/SSW.SophieBot/dialogs/GetPeopleBySkills/GetPeopleBySkills.dialog.schema
  src/bot/SSW.SophieBot/dialogs/GetPeopleBySkills/language-generation/en-us/GetPeopleBySkills.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/bot/SSW.SophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/bot/SSW.SophieBot/settings/cross-train.config.json
Labels: bug

#357 fix: people list card error
  src/bot/SSW.SophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/common.en-us.lg
Labels: bug

#358 Fix profile card buttons hiding problem
  src/bot/SSW.SophieBot/language-generation/en-us/profile.en-us.lg
Labels: bug

#359 Fix note appear when skill exists
  src/bot/SSW.SophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
Labels: bug

#364 Improve LUIS model for GetCurrentEmployeesOnLocation intent
  src/bot/SSW.SophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug

#368 Add calcauted time
  src/bot/SSW.SophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesWithFreeDateAction.cs
  src/bot/SSW.SophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
  src/bot/SSW.SophieBot.HttpClientComponents.PersonQuery/Models/EmployeeWithFreeDateModel.cs
  src/bot/SSW.SophieBot/dialogs/GetFreeDayDialog/language-generation/en-us/GetFreeDayDialog.en-us.lg
Labels: enhancement

#367 Enhance profile and availability card
  src/bot/SSW.SophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/common.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/icons.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/profile.en-us.lg
Labels: enhancement

#370 Temporary fix for GetPeopleBySkills bug
  src/bot/SSW.SophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug

#375 Update show calendar query to use authentication
  src/bot/SSW.SophieBot/dialogs/GetCalendarDialog/GetCalendarDialog.dialog
  src/bot/SSW.SophieBot/dialogs/GetCalendarDialog/language-generation/en-us/GetCalendarDialog.en-us.lg
Labels: Type: Bug

#377 Refactor adaptive cards
  src/bot/SSW.SophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetCalendarDialog/language-generation/en-us/GetCalendarDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/language-generation/en-us/GetCurrentEmployeesOnLocationDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetEmailAddressDialog/language-generation/en-us/GetEmailAddressDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetFreeDayDialog/language-generation/en-us/GetFreeDayDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetPeopleBySkills/language-generation/en-us/GetPeopleBySkills.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetPhoneNumberDialog/language-generation/en-us/GetPhoneNumberDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetProfileDialog/language-generation/en-us/GetProfileDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GetSkillsDialog/language-generation/en-us/GetSkillsDialog.en-us.lg
  src/bot/SSW.SophieBot/dialogs/GreetingDialog/language-generation/en-us/GreetingDialog.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/agenda.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/common.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/greeting.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/groupList.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/peopleList.en-us.lg
Labels: enhancement
