Repository SSWConsulting/SSW.SophieBot, pull requests merged in 2021-11, with the labels that each got.

#212 Data correction for GetCurrentEmployeesOnLocation dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/GetCurrentEmployeesOnLocationDialog.dialog
Labels: bug

#213 Data correction for GetCurrentEmployeesOnLocation dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/GetCurrentEmployeesOnLocationDialog.dialog
Labels: bug

#214 Re-apply dialog logic in GetPhoneNumber
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPhoneNumberDialog/GetPhoneNumberDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPhoneNumberDialog/language-generation/en-us/GetPhoneNumberDialog.en-us.lg
Labels: enhancement

#215 Enhance pagination display
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#216 Re-apply dialog logic in GetEmailAddress
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/GetEmailAddressDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/language-generation/en-us/GetEmailAddressDialog.en-us.lg
Labels: enhancement

#219 Refine billable list card, enhance LUIS model
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug, enhancement

#218 LUIS model enhancement
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: enhancement

#220 Add tenant authentication
  src/SSW.SophieBot/SSWSophieBot/Integration/SSWSophieBotAdapter.cs
  src/SSW.SophieBot/SSWSophieBot/Integration/SSWSophieBotTelemetryInitializer.cs
  src/SSW.SophieBot/SSWSophieBot/Middlewares/TeamsTenantAuthenticationMiddleware.cs
  src/SSW.SophieBot/SSWSophieBot/Startup.cs
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/SSWSophieBot/settings/ApplicationSettings.cs
  src/SSW.SophieBot/SSWSophieBot/settings/appsettings.example.json
  src/SSW.SophieBot/SSWSophieBot/wwwroot/sophiebot-branding.svg
Labels: enhancement, feature

#222 Enhance LUIS model for sites
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug

#221 Refine list cards
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
Labels: enhancement

#225 Refactor dev calculation logic
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetEmployeeModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/ProfileCategory.cs
Labels: enhancement

#226 Fix project name match bug
  _docs/images/goal_user-entity.png
  _docs/images/goal_user-related.png
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProjectsFromQueryAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
Labels: bug

#227 Refine billable hours calculation logic
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
Labels: bug

#229 Refine GetEmployeesByProject logic and enhance LUIS model
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: enhancement

#228 Refactor on leave logic
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetAppointmentModel.cs
Labels: enhancement

#234 Refine pagination for GetPeopleBasedOnLocation
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#235 Refine LUIS model
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug

#238 Add Teams user name to telemetry
  src/SSW.SophieBot/SSWSophieBot/Integration/SSWSophieBotTelemetryInitializer.cs
Labels: enhancement

#244 Fix DI scope issue
  src/SSW.SophieBot/SSWSophieBot/Integration/SSWSophieBotTelemetryInitializer.cs
Labels: bug

#245 Add inoffice param for GetExpertsByLocation query
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
Labels: bug

#246 Add person name auto-correction for GetSkills dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/GetCurrentEmployeesOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/GetEmailAddressDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetSkillsDialog/GetSkillsDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetSkillsDialog/GetSkillsDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetSkillsDialog/language-generation/en-us/GetSkillsDialog.en-us.lg
Labels: enhancement

#255 Enhance make billed column more understandable
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
Labels: enhancement

#254 Add fallback to GetExpertsByLocation dialog
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/GetPeopleBySkills.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/language-generation/en-us/GetPeopleBySkills.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug, enhancement

#256 Make client left align and fix query failed issue
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
Labels: enhancement, Sprint 11

#259 Expand search if no one is found
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
Labels: enhancement

#258 Update Project Info button urls, remove separators for list cards
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/SSWSophieBot/settings/ApplicationSettings.cs
  src/SSW.SophieBot/SSWSophieBot/settings/appsettings.example.json
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProjectsFromQueryAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetEmployeeProjectModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/ProjectWithEmployeesCountModel.cs
Labels: enhancement

#262 Fix timezone issue when calculating free days
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
Labels: bug

#261 Add site entity
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug

#260 Fix potential errors
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProjectsFromQueryAction.cs
Labels: bug

#265 Add generic answer for report bugs query
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: enhancement

#266 Refine profile card and greeting message
  src/SSW.SophieBot/SSWSophieBot/Middlewares/TeamsAuthenticationMiddleware.cs
  src/SSW.SophieBot/SSWSophieBot/Startup.cs
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/greeting.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/icons.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
  src/SSW.SophieBot/components/SSWSophieBot.Components/ComponentHelper.cs
Labels: enhancement

#267 Change availability format
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
Labels: enhancement

#268 Show location buttons directly
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/language-generation/en-us/GetPeopleBySkills.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#270 Fix authentication issue
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog
Labels: bug

#275 Make notes more precise
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#269 Add badges to README
  README.MD
Labels: documentation

#276 Enhance is adam booked or free
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/common.en-us.lg
Labels: enhancement

#277 Code cleanup
  src/SSW.SophieBot/SSWSophieBot/Controllers/BotController.cs
  src/SSW.SophieBot/SSWSophieBot/Controllers/SkillController.cs
  src/SSW.SophieBot/SSWSophieBot/Integration/SophieBotAdapter.cs
  src/SSW.SophieBot/SSWSophieBot/Integration/SophieBotTelemetryInitializer.cs
  src/SSW.SophieBot/SSWSophieBot/Program.cs
  src/SSW.SophieBot/SSWSophieBot/Startup.cs
  src/SSW.SophieBot/SSWSophieBot/settings/appsettings.example.json
  src/SSW.SophieBot/components/SSWSophieBot.Components/ComponentHelper.cs
  src/SSW.SophieBot/components/SSWSophieBot.Components/Components/CommonComponent.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByBillableAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProfileWithBookingInfoAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProjectsFromQueryAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetEmployeeModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/ProjectWithEmployeesCountModel.cs
Labels: enhancement

#274 Enhance bug report response
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/SSWSophieBot/settings/ApplicationSettings.cs
  src/SSW.SophieBot/SSWSophieBot/settings/appsettings.example.json
Labels: enhancement

#281 Enhance report bugs reponse text
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#282 Enhance profile card
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/agenda.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/icons.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
Labels: enhancement

#283 Enhance calendar and project employee list card
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/agenda.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
Labels: enhancement

#286 Fix query error - is adam booked
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
Labels: bug

#287 Enhance LUIS model for GetSkills intent
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug

#288 Enhance who is in sydney
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/GetCurrentEmployeesOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/language-generation/en-us/GetCurrentEmployeesOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/GetPeopleBasedOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/common.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/groupList.en-us.lg
Labels: enhancement

#292 Fix NPE caused by null regarding
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
Labels: bug

#291 Enhance who is adam cogan
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCalendarDialog/language-generation/en-us/GetCalendarDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug, enhancement

#289 Track submit actions usage
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCalendarDialog/language-generation/en-us/GetCalendarDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/language-generation/en-us/GetCurrentEmployeesOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/language-generation/en-us/GetEmailAddressDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetFreeDayDialog/language-generation/en-us/GetFreeDayDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/language-generation/en-us/GetPeopleBySkills.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPhoneNumberDialog/language-generation/en-us/GetPhoneNumberDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetProfileDialog/language-generation/en-us/GetProfileDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetSkillsDialog/language-generation/en-us/GetSkillsDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GreetingDialog/language-generation/en-us/GreetingDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/common.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/groupList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
Labels: enhancement

#296 Enhance who is free next friday in melbourne with angular skils
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
Labels: enhancement

#309 Enhance LUIS model for getting person information
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug

#290 fix date issue
  src/SSW.SophieBot/components/SSWSophieBot.Components/ComponentHelper.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetFreeEmployeesAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetInternalBookedEmployeesAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
Labels: bug

#317 Add date to query - who is wroking for ssw
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog
Labels: enhancement

#313 Remove blank spaces when skills not exist
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetSkillsDialog/language-generation/en-us/GetSkillsDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/common.en-us.lg
Labels: enhancement

#312 Support query - who is free today with react skills
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/GetAvailableExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
Labels: enhancement

#293 Adjust card style and fix date issue
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetFreeDayDialog/language-generation/en-us/GetFreeDayDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/common.en-us.lg
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
Labels: enhancement

#318 Add issue and pr templates
  .github/ISSUE_TEMPLATE/0-feature.md
  .github/ISSUE_TEMPLATE/1-bug.md
  .github/ISSUE_TEMPLATE/2-docs.md
  .github/ISSUE_TEMPLATE/3-refactor.md
  .github/ISSUE_TEMPLATE/4-devops.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
Labels: feature

#331 Removing trailing full stops in profile card
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
Labels: enhancement

#337 Support "I need help with Azure"
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug

#334 Feat when is calum free
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetFreeDayDialog/language-generation/en-us/GetFreeDayDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/agenda.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/common.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
Labels: feature

#336 Enhance luis to recognize kaique
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug

#340 Hide buttons in profile card for external users
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/settings/appsettings.example.json
Labels: enhancement

#341 Change calendar card title
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/agenda.en-us.lg
Labels: bug

#344 Enhance luis for show calendar intent
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: feature

#343 Fix teams message exceeds size limit
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/common.en-us.lg
Labels: bug

#348 Fix GitHub workflow
  .github/workflows/SSW.SophieBot.dev.yml
Labels: bug

#346 Fix missing office selection card
  src/bot/SSW.SophieBot/SSW.SophieBot.csproj
  src/bot/SSW.SophieBot/SSWSophieBot.dialog
  src/bot/SSW.SophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog
  src/bot/SSW.SophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog.schema
  src/bot/SSW.SophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/bot/SSW.SophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/bot/SSW.SophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/bot/SSW.SophieBot/settings/cross-train.config.json
Labels: bug

#351 fix: make last seen more accurate
  src/bot/SSW.SophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
Labels: bug
