Repository SSWConsulting/SSW.SophieBot, pull requests merged in 2021-10, with the labels that each got.

#123 Improve card consistency
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/language-generation/en-us/GetCurrentEmployeesOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/groupList.en-us.lg
Labels: enhancement

#124 Refine response card
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/GetAvailableExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
Labels: enhancement

#133 Change trigger type of prod deployment to workflow_dispatch
  .github/workflows/SSW.SophieBot.prod.yml
Labels: enhancement

#151 Fix who is on client work
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/EmployeeByDateModel.cs
Labels: bug

#155 Refine response list and refine LUIS model
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/language-generation/en-us/GetPeopleBySkills.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetFreeEmployeesAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/EmployeeBillableItemModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/EmployeeByDateModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/FreeEmployeeModel.cs
Labels: enhancement

#158 Refine response message of get email query, add person name confirmation
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/GetEmailAddressDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/language-generation/en-us/GetEmailAddressDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/language-understanding/en-us/GetEmailAddressDialog.en-us.lu
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/recognizers/GetEmailAddressDialog.lu.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/recognizers/GetEmailAddressDialog.lu.qna.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPhoneNumberDialog/GetPhoneNumberDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPhoneNumberDialog/language-generation/en-us/GetPhoneNumberDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/schemas/sdk.schema
  src/SSW.SophieBot/components/SSWSophieBot.Components/Actions/PersonNameAlterateAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.Components/Actions/PersonNameAlterateAction.schema
  src/SSW.SophieBot/components/SSWSophieBot.Components/Actions/StringJoinAction.schema
  src/SSW.SophieBot/components/SSWSophieBot.Components/Components/Component.cs
Labels: bug, enhancement

#160 Add Free for booking status, refactor helper methods, refine logics in dialogs
  src/SSW.SophieBot/SSWSophieBot/.gitignore
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/GetAvailableExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/GetCurrentEmployeesOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetFreeEmployeesAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetInternalBookedEmployeesAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProfileWithStatusAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/BookingStatus.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/EmployeeBillableItemModel.cs
Labels: enhancement

#162 Fix show all bug
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/GetPeopleBySkills.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/language-generation/en-us/GetPeopleBySkills.en-us.lg
Labels: bug

#166 Refine greeting message
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/greeting.en-us.lg
Labels: enhancement

#167 Refine email address rendering, enhance LUIS model
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/language-generation/en-us/GetEmailAddressDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: bug, enhancement

#168 Refine email address rendering for profile card
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
Labels: enhancement

#170 Refine booking status logic
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProfileWithStatusAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
Labels: enhancement
