Repository SSWConsulting/SSW.SophieBot, pull requests merged in 2021-08, with the labels that each got.

#3 Add Utc format custom action
  src/SSW.SophieBot/SSWSophieBot/.editorconfig
  src/SSW.SophieBot/SSWSophieBot/Microsoft/Extensions/Configuration/BotConfigurationBuilderExtensions.cs
  src/SSW.SophieBot/SSWSophieBot/Program.cs
  src/SSW.SophieBot/SSWSophieBot/actions/UtcConvert/UtcConvertAction.cs
  src/SSW.SophieBot/SSWSophieBot/actions/UtcConvert/UtcConvertAction.schema
  src/SSW.SophieBot/SSWSophieBot/actions/UtcConvert/UtcConvertActionBotComponent.cs
  src/SSW.SophieBot/SSWSophieBot/schemas/sdk.schema
  src/SSW.SophieBot/SSWSophieBot/settings/botsettings.json
Labels: enhancement

#6 move custom action to new project
  src/SSW.SophieBot/SSWSophieBot.UtcConvertAction/SSWSophieBot.UtcConvertAction.csproj
  src/SSW.SophieBot/SSWSophieBot.UtcConvertAction/UtcConvertAction.cs
  src/SSW.SophieBot/SSWSophieBot.UtcConvertAction/UtcConvertAction.schema
  src/SSW.SophieBot/SSWSophieBot.UtcConvertAction/UtcConvertActionBotComponent.cs
  src/SSW.SophieBot/SSWSophieBot.sln
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.csproj
  src/SSW.SophieBot/SSWSophieBot/schemas/sdk.schema
  src/SSW.SophieBot/SSWSophieBot/settings/appsettings.example.json
Labels: enhancement

#5 Add static files and GitHub action for SophieBot.Web
  .github/workflows/SSW.SophieBot.Web.yml
  README.MD
  src/SSW.SophieBot.Web/.gitignore
  src/SSW.SophieBot.Web/README.md
  src/SSW.SophieBot.Web/package.json
  src/SSW.SophieBot.Web/src/index.css
  src/SSW.SophieBot.Web/src/index.html
  src/SSW.SophieBot.Web/src/index.js
  src/SSW.SophieBot.Web/yarn.lock
Labels: enhancement

#7 Add custom http request component
  src/SSW.SophieBot/SSWSophieBot.sln
  src/SSW.SophieBot/SSWSophieBot/Microsoft/Extensions/Configuration/BotConfigurationBuilderExtensions.cs
  src/SSW.SophieBot/SSWSophieBot/Program.cs
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.csproj
  src/SSW.SophieBot/SSWSophieBot/Startup.cs
  src/SSW.SophieBot/SSWSophieBot/schemas/sdk.schema
  src/SSW.SophieBot/SSWSophieBot/settings/appsettings.example.json
  src/SSW.SophieBot/SSWSophieBot/settings/botsettings.json
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.Abstractions/HttpClientActionBase.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.Abstractions/HttpClientBase.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.Abstractions/HttpClientOptions.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.Abstractions/HttpClientServiceCollectionExtensions.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.Abstractions/SSWSophieBot.HttpClientComponents.Abstractions.csproj
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProfileAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProfileAction.schema
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Clients/GetProfileClient.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Components/GetProfileBotComponent.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetAppointmentModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetDeviceModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetEmployeeModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetEmployeeProjectModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetLastSeenAtSiteModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetLocationModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetSkillModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/PersonQueryClientServiceCollectionExtensions.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/SSWSophieBot.HttpClientComponents.PersonQuery.csproj
  src/SSW.SophieBot/components/SSWSophieBot.TimeComponents/Actions/UtcConvertAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.TimeComponents/Actions/UtcConvertAction.schema
  src/SSW.SophieBot/components/SSWSophieBot.TimeComponents/Components/UtcConvertBotComponent.cs
  src/SSW.SophieBot/components/SSWSophieBot.TimeComponents/SSWSophieBot.TimeComponents.csproj
Labels: enhancement

#8 Replace user input prompt with custom http caller
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/GetEmailAddressDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/language-generation/en-us/GetEmailAddressDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/GetPeopleBasedOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPhoneNumberDialog/GetPhoneNumberDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPhoneNumberDialog/language-generation/en-us/GetPhoneNumberDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetProfileDialog/GetProfileDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetProfileDialog/language-generation/en-us/GetProfileDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetSkillsDialog/GetSkillsDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetSkillsDialog/language-generation/en-us/GetSkillsDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/schemas/sdk.schema
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.Abstractions/DialogContextExtensions.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.Abstractions/HttpClientActionBase.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.Abstractions/HttpClientBase.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProfileAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProfileAction.schema
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Clients/GetProfileClient.cs
Labels: enhancement

#10 A line per person for Who is in Melbourne
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/GetPeopleBasedOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg
Labels: enhancement

#9 Add goodbye flow
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/SSWSophieBot/settings/cross-train.config.json
Labels: feature

#12 fix: people list number missing
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/GetPeopleBasedOnLocationDialog.dialog
Labels: bug

#11 Add input validation for custom Utc convert action
  src/SSW.SophieBot/components/SSWSophieBot.TimeComponents/Actions/UtcConvertAction.cs
Labels: bug

#13 feat: update direct line config
  src/SSW.SophieBot.Web/src/index.js
Labels: feature
