Repository SSWConsulting/SSW.SophieBot, pull requests merged in 2021-09, with the labels that each got.

#47 Add person name validation for GetProfile dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetProfileDialog/GetProfileDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetProfileDialog/language-generation/en-us/GetProfileDialog.en-us.lg
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProfileAction.cs
Labels: bug

#44 Add hey this is broken dialog
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/GetAvailableExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/SSWSophieBot/settings/cross-train.config.json
Labels: feature

#50 Fix adaptive card display issue on Teams
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/workingList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByProjectAction.cs
Labels: bug

#55 Add last seen info for Is Anthony Nguyen booked or free query
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/CheckAvailabilityDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/CheckAvailabilityDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/GetAvailableExpertsByLocationDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/GetEmailAddressDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetManagerDialog/GetManagerDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/GetPeopleBasedOnLocationDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/GetPeopleBySkills.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPhoneNumberDialog/GetPhoneNumberDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetProfileDialog/GetProfileDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetSkillsDialog/GetSkillsDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/ResolveUserDialog/ResolveUserDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/schemas/sdk.schema
  src/SSW.SophieBot/components/SSWSophieBot.Components/Actions/TimeDifferenceAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.Components/Actions/TimeDifferenceAction.schema
  src/SSW.SophieBot/components/SSWSophieBot.Components/Components/Component.cs
Labels: enhancement

#56 Change goodbye query response
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#57 Add Who works in Melbourne query
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/GetPeopleBasedOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/workingList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/schemas/sdk.schema
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/EmployeesGroupKey.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/EmployeesGroupOptionsExpression.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/EmployeesHelper.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByBillableAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByBillableAction.schema
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByProjectAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetGroupedEmployeesAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetGroupedEmployeesAction.schema
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/SkillExpression.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Components/HttpClientComponent.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/EmployeeBillableItemModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/EmployeesByProjectListModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GroupedEmployeesModel.cs
Labels: feature

#60 User gravatar to get missing avatars in GetProfile action
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetProfileAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Clients/GravatarManager.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Clients/IAvatarManager.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Components/HttpClientComponent.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/PersonQueryClientServiceCollectionExtensions.cs
Labels: enhancement

#66 Remove the test dialog for GetCurrentEmployeesOnLocation query
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/GetCurrentEmployeesOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/language-generation/en-us/GetCurrentEmployeesOnLocationDialog.en-us.lg
Labels: bug

#67 Remove skill info in billable employee list card title
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
Labels: enhancement

#63 Improve handling for unknown queries
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: enhancement

#62 Refine response message when employees are single or multiple
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
Labels: enhancement

#65 Queries contain locations
  src/SSW.SophieBot/SSWSophieBot/.gitignore
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/icons.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/SSWSophieBot/schemas/sdk.schema
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.schema
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Components/HttpClientComponent.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/EmployeeByDateModel.cs
Labels: feature

#61 Refine response for bug report query
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#68 Add email highlight for goodbye response
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#71 Refine email address in bug report response
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#73 Refine Who is free next friday in melbourne with angular skills
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/GetAvailableExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/components/SSWSophieBot.Components/Actions/TimeFormatAction.cs
Labels: enhancement

#75 Add greeting intent to respond to greetings
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GreetingDialog/GreetingDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GreetingDialog/knowledge-base/en-us/GreetingDialog.en-us.qna
  src/SSW.SophieBot/SSWSophieBot/dialogs/GreetingDialog/language-generation/en-us/GreetingDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GreetingDialog/language-understanding/en-us/GreetingDialog.en-us.lu
  src/SSW.SophieBot/SSWSophieBot/dialogs/GreetingDialog/recognizers/GreetingDialog.en-us.lu.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GreetingDialog/recognizers/GreetingDialog.lu.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GreetingDialog/recognizers/GreetingDialog.lu.qna.dialog
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
  src/SSW.SophieBot/SSWSophieBot/settings/cross-train.config.json
Labels: enhancement, feature

#77 Refine GetAvailableExpertsOnLocation intent
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: enhancement

#78 Refine GetAvailableExpertsOnLocation dialog response
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
Labels: enhancement

#80 Filter out people on leave
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.cs
Labels: enhancement

#81 Add timezone check in GetEmployeesByDate action
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.cs
Labels: enhancement

#86 Add full name recognition
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/CheckAvailabilityDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/GetEmailAddressDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmailAddressDialog/language-generation/en-us/GetEmailAddressDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPhoneNumberDialog/GetPhoneNumberDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPhoneNumberDialog/language-generation/en-us/GetPhoneNumberDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetProfileDialog/GetProfileDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetProfileDialog/language-generation/en-us/GetProfileDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetSkillsDialog/GetSkillsDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetSkillsDialog/language-generation/en-us/GetSkillsDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/profile.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: enhancement

#87 Refine response message for available experts by location
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
Labels: enhancement

#92 Add skill entity validation for GetPeopleBySkills dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/GetPeopleBySkills.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/language-generation/en-us/GetPeopleBySkills.en-us.lg
Labels: enhancement

#93 Add datetime entity type validation for date related queries
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
Labels: bug

#95 Refinements for GetCurrentEmployeesOnLocation dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/GetCurrentEmployeesOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/language-generation/en-us/GetCurrentEmployeesOnLocationDialog.en-us.lg
Labels: enhancement

#96 Refine response message for GetPeopleBasedOnLocation dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg
Labels: enhancement

#94 Enhance who is on client work
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/icons.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/schemas/sdk.schema
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetFreeEmployeesAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetFreeEmployeesAction.schema
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Components/HttpClientComponent.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/FreeEmployeeModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/NextClientModel.cs
Labels: enhancement

#100 Refine response message for unknown intents
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#103 Refine response message for bug report
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/SSWSophieBot.en-us.lg
Labels: enhancement

#101 Enhance #16 #18 #19 #21
  src/SSW.SophieBot/SSWSophieBot/dialogs/CheckAvailabilityDialog/language-generation/en-us/CheckAvailabilityDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/settings/appsettings.example.json
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.cs
Labels: enhancement

#99 Refine response message
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/GetAvailableExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetGroupedEmployeesAction.cs
Labels: enhancement

#104 Fix message size too big error
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/GetEmployeesByProjectDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBySkills/language-generation/en-us/GetPeopleBySkills.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/GetPeopleOnClientWorkDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleOnClientWorkDialog/language-generation/en-us/GetPeopleOnClientWorkDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
Labels: bug

#108 Change skill card style
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
Labels: enhancement

#109 Refine response message for who-is-in-the-sydney-office-right-now query
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/GetCurrentEmployeesOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/language-generation/en-us/GetCurrentEmployeesOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetEmployeesByProjectDialog/language-generation/en-us/GetEmployeesByProjectDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/language-generation/en-us/GetExpertsByLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/GetPeopleBasedOnLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/groupList.en-us.lg
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetEmployeesByDateAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/EmployeesHelper.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/EmployeeBillableItemModel.cs
Labels: enhancement

#111 Refine employee list card style
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/billableList.en-us.lg
Labels: enhancement

#112 Add pagination for query - Who is free next Friday in Melbourne with Angular skills?
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/GetAvailableExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
Labels: bug

#113 Fix the data mismatch issue
  src/SSW.SophieBot/SSWSophieBot/SSWSophieBot.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetCurrentEmployeesOnLocationDialog/language-generation/en-us/GetCurrentEmployeesOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetExpertsByLocationDialog/GetExpertsByLocationDialog.dialog.schema
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetPeopleBasedOnLocationDialog/language-generation/en-us/GetPeopleBasedOnLocationDialog.en-us.lg
  src/SSW.SophieBot/SSWSophieBot/language-generation/en-us/groupList.en-us.lg
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Actions/GetGroupedEmployeesAction.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetEmployeeModel.cs
  src/SSW.SophieBot/components/SSWSophieBot.HttpClientComponents.PersonQuery/Models/GetSkillModel.cs
Labels: enhancement

#114 Fix 400 error when displaying list card on teams
  src/SSW.SophieBot/SSWSophieBot/dialogs/GetAvailableExpertsByLocationDialog/language-generation/en-us/GetAvailableExpertsByLocationDialog.en-us.lg
Labels: bug

#116 Refine LUIS model for who-is-on-client-work
  src/SSW.SophieBot/SSWSophieBot/language-understanding/en-us/SSWSophieBot.en-us.lu
Labels: enhancement

#85 Add Github Actions workflow files
  .github/workflows/SSW.SophieBot.dev.yml
  .github/workflows/SSW.SophieBot.prod.yml
  .github/workflows/scripts/Build-LUIS.ps1
  .github/workflows/scripts/Build-Orchestrator.ps1
  .github/workflows/scripts/LUUtils.ps1
  .github/workflows/scripts/Publish-WebApp.ps1
  .github/workflows/scripts/PublishUtils.ps1
Labels: enhancement
